### ISSUE TITLE
[Question] - Command split

### ISSUE THREAD

**Issue by samber** [eleme/corvus#117]
Hi,

First, thanks for you great work! :tada:

Why do you do command splitting ?
Is it to reduce redis lock time of large MGET/MSET/DEL/... ?
Did you make some measurements ?

**Comment by doyoubi** [comment]
Sorry, I think I'm not fully understand the ```redis lock time``` you said.
Note that in redis cluster, all the keys in `MGET/MSET...` must be in the same shard. A large MGET will block the single node for a long time, which can have great impact on other requests in this node.

**Comment by samber** [comment]
ok, I understand why you split: to read or write from multiple redis shards in the same command ;)

Thanks
