### ISSUE TITLE
Will corvus handle cluster state on slot movements

### ISSUE THREAD

**Issue by mstaack** [eleme/corvus#118]
I am using this from a php client.

If some slots move to another node... redis-cluster usually tells me with MOVED ip:port response.

Does corvus maintain these informations so requests for this slot will then be redirected by corvus to the correct new node?

Idea is to prevent the redirect/connect overhead if slots are moved...

thanks max

**Comment by tevino** [comment]
Yes, that's what Corvus is for.
Just use an ordinary Redis 2.0 client and Corvus will do the work for you.

**Comment by mstaack** [comment]
@tevino thats awesome!
