### ISSUE TITLE
Allow listening on non-0.0.0.0 interface

### ISSUE THREAD

**Issue by badboy** [eleme/corvus#120]
[Currently corvus always listens on 0.0.0.0](https://github.com/eleme/corvus/blob/ed3ad26466cc97d735d550882501e06bd835dde3/src/corvus.c#L279), making it globally reachable over the machine's interfaces.
Additionally, the configuration parameter is called `bind` but sets the port corvus listens on.

It would be desirable to be able to configure the interface to listen to for incoming connection (e.g. 127.0.0.1 aka localhost only).
Redis also uses `bind` for the interfaces and `port` for the actual port it is listening to.

In addition, this would make it possible to add IPv6 support as well.

**Comment by badboy** [comment]
I added support for this and prelimanary IPv6 support (at least listening) in my branch here: https://github.com/badboy/corvus/tree/with-bind-and-port

**Comment by tevino** [comment]
Great idea, you are welcome to submit a PR, I did it for you, please feel free to do anything about it:
https://github.com/eleme/corvus/pull/121

**Comment by badboy** [comment]
I expected it to be more work initially and it will certainly affect users. But the PR is there now. Let's move discussion over there.
