### ISSUE TITLE
Redis 4 Support

### ISSUE THREAD

**Issue by mstaack** [eleme/corvus#127]
Whats the status of using latest redis 4 with this proxy?

Cheers Max

**Comment by doyoubi** [comment]
The only two ways that corvus interacts with redis are `CLUSTER NODES` and other data manipulating commands. Redis 4 changed its `CLUSTER NODES` format but after merging #124 corvus should be able to be compatible with redis 4. I've done some minor tests but we have NOT fully tested redis 4 in our production environment and new commands introduced in 3.2 and 4.0 are not supported yet for the current corvus.
We will fix the CI test and merge #124 in the comming Monday.

**Comment by mstaack** [comment]
@doyoubi thx! will give a try soon
