### ISSUE TITLE
Do you have a plan for supporting backend redis cluster configed with requirepass?

### ISSUE THREAD

**Issue by airhuman** [eleme/corvus#134]
Hello,

With v0.2.7 tag and redis-cluster which is configured with requirepass.
Found that the corvus  doesn't send AUTH command to the backend redis cluster instance.
So I got "(error) NOAUTH Authentication required."

Twemproxy has redis_auth configuration which implements "Authenticate to the Redis server on connect."

Thanks!

**Comment by doyoubi** [comment]
No, we're not going to support it.
Using password in redis makes it quite hard to maintain the cluster and we're not sure whether the plain text password stored in every machine can really protect the cluster.

**Comment by airhuman** [comment]
Okay.
Anyway, thanks for your reply.
