### ISSUE TITLE
corvus是否支持ssdb或者pika？

### ISSUE THREAD

**Issue by 527593036** [eleme/corvus#142]
corvus是否支持ssdb或者pika？

**Comment by doyoubi** [comment]
corvus是用来适配[Redis Cluster](https://redis.io/topics/cluster-tutorial)的, 不支持[ssdb](https://github.com/ideawu/ssdb)和[pika](https://github.com/Qihoo360/pika).

corvus does not support [ssdb](https://github.com/ideawu/ssdb) and [pika](https://github.com/Qihoo360/pika).

**Comment by 527593036** [comment]
非常感谢
