### ISSUE TITLE
corvus health check

### ISSUE THREAD

**Issue by rpallikonda** [eleme/corvus#145]
Any suggestions on how to implement a simple prometheus health check for corvus?

I tried a simple TCP 'PING' request and expected 'PONG', but that didn't work.

Please share a simple 'telnet' or 'netcat' example command line for the suggestion. I can use that to automate the check on my end.

**Comment by doyoubi** [comment]
Unlike Redis, corvus just supports the [RESP protocol](https://redis.io/topics/protocol).
You can use any redis client library or the `redis-cli` binary to send the PING request.

**Comment by rpallikonda** [comment]
@doyoubi  I do not want to bundle the redis-cli tool with the prometheus application (which does the health check).

I tried emulating the RESP payload on a plain TCP connection, but couldn't get it to working.

I addressed my issue by enabling the statsd metrics in corvus, and deploying prometheus statsd exporter to do the health check.

Thank you for your suggestion.
