### ISSUE TITLE
Awesome stuff!

### ISSUE THREAD

**Issue by FGRibreau** [eleme/corvus#41]
Awesome stuff @maralla @xinming90 !

Corvus will be shared in our next [RedisWeekly](http://redisweekly.com/)! Once published (in a matter of minutes) you will be able to see your [project here](http://redisweekly.com/archive/141.html) :)

**Comment by wooparadog** [comment]
@FGRibreau Thanks for sharing! It meant a lot to us that it is accepted in the redis community.
