### ISSUE TITLE
document seems needs to more explain

### ISSUE THREAD

**Issue by LiSheep** [eleme/corvus#76]
Corvus seems a good job, but I cannot understand what corvus' config file, and what corvus' cluster exactly means, and I also can't understand the logic of corvus.
there are some questions,
1.  Dose it support sharding with hashtag like twemproxy?
2.  How to config redis cluster?
for example, i have 2 master redis(:6000 :7000) with some slaves(use the cmd of slaveof :7000). then should I config it as below(I tried and seems wrong...)?
`bind 1000
node localhost:6301,localhost:7000
thread 4`

Could you kindly explain to us. Many Thanks!

**Comment by wooparadog** [comment]
Please refer to the official redis cluster documentation and tutorials:

http://redis.io/topics/cluster-spec
http://redis.io/topics/cluster-tutorial
