### ISSUE TITLE
Functional enhancement

### ISSUE THREAD

**Issue by sumonsun** [eleme/corvus#78]
Do you have any plan do below function?

1. Traffic restrictions,like ops ,connection
2. Blacklist,White-list
3. Copy and distribute traffic

**Comment by wooparadog** [comment]
> Traffic restrictions,like ops ,connection
> Blacklist,White-list

We have implemented `auth` for scenarios like that, which I think is sufficient enough.

> Copy and distribute

No, we are not planning to support this. There is https://github.com/vipshop/redis-migrate-tool which may suit the role for replicating data.
