### ISSUE TITLE
support for redis 3.2?

### ISSUE THREAD

**Issue by timfeirg** [eleme/corvus#89]
I wonder if supporting higher versions of redis is on the roadmap? it'd be awesome to see the new features introduced by redis 3.2.

**Comment by doyoubi** [comment]
Redis 3.2 provides some good features and supporting them may be just adding some new items to command table. But actually there is no 3.2 in our production environment and I think supporting 3.2 needs further tests. We are trying new redis version in progress but we will not support it very soon.

**Comment by badboy** [comment]
Is this just about newly introduced commands in 3.2?
The Cluster API should be fairly stable between 3.0 and 3.2 (I didn't check whether the output of CLUSTER NODES changed, I will do so tomorrow)

**Comment by doyoubi** [comment]
Yes, it's all about the new commands.
As long as the `CLUSTER NODES`, `ASK(ING)`, `MOVED` are not changed, corvus should be able to work with redis 3.2.

**Comment by badboy** [comment]
`CLUSTER NODES` is the same in 3.0 and 3.2 so corvus should be able to work with Redis 3.2 without problems

**Comment by badboy** [comment]
So `CLUSTER NODES` is the same in 3.0 and 3.2, but it changed in unstable (it appends `@<busport>`.
In order to be forwards-compatible corvus could already add a check for that or switch to the more stable `CLUSTER SLOTS` API instead.

**Comment by doyoubi** [comment]
In fact we used `CLUSTER SLOTS` before #64 . The problem is after the large clusters scale up and down for several times, the slot ranges will be broken into small pieces and the response of `CLUSTER SLOTS` can be large and cause performance problem.

**Comment by joshweir** [comment]
Can I assume that corvus v0.2.7 supports Redis 3.2? The release notes mention that Redis 4 is supported. Just wondering why this issue is still open? Thanks.

**Comment by doyoubi** [comment]
@joshweir corvus v0.2.7 is just compatible with Redis 3.2 and 4, but still doesn't support new commands of them.
Sorry for the misleading release notes. I will update it.

**Comment by joshweir** [comment]
@doyoubi It's no problem. Thanks for the clarification.
